# Generated by Django 5.0.2 on 2024-02-14 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
