# Generated by Django 5.0.2 on 2024-02-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_codebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_codebar',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
