# Generated by Django 5.0.2 on 2024-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productaction',
            name='invoice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productaction',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
