# Generated by Django 5.0.2 on 2024-03-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaction',
            name='invoice',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
