# Generated by Django 5.0.2 on 2024-03-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productaction_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productchangelog',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='productchangelog',
            name='changed_by',
        ),
    ]
