# Generated by Django 5.0.2 on 2024-04-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_family_family_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='last_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
