# Generated by Django 5.0.2 on 2024-04-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_alter_family_last_delivery_alter_family_last_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
