# Generated by Django 5.0.2 on 2024-04-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_alter_family_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_manager',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
