# Generated by Django 5.0.2 on 2024-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_alter_family_family_manager_alter_family_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyaction',
            name='status',
        ),
        migrations.AddField(
            model_name='familyaction',
            name='product_packing',
            field=models.CharField(choices=[], default='', max_length=255),
        ),
    ]
