# Generated by Django 5.0.2 on 2024-04-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_remove_familyaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyaction',
            name='product',
            field=models.CharField(choices=[], default='', max_length=255),
        ),
    ]
