# Generated by Django 5.0.2 on 2024-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_alter_familyaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyaction',
            name='status',
            field=models.CharField(default='Pendente', max_length=255),
        ),
        migrations.AlterField(
            model_name='familyaction',
            name='metal_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familyaction',
            name='product',
            field=models.CharField(choices=[('Ardox Polido | 18x30', 'Ardox Polido | 18x30'), ('Ardox Galvanizado | 18x30', 'Ardox Galvanizado | 18x30')], max_length=255),
        ),
        migrations.AlterField(
            model_name='familyaction',
            name='product_packing',
            field=models.CharField(choices=[('Ardox Polido | 18x30 | 1 Kg', 'Ardox Polido | 18x30 | 1 Kg'), ('Ardox Polido | 18x30 | 500 Kg', 'Ardox Polido | 18x30 | 500 Kg'), ('Ardox Galvanizado | 18x30 | 1 Kg', 'Ardox Galvanizado | 18x30 | 1 Kg'), ('Ardox Galvanizado | 18x30 | 500 Kg', 'Ardox Galvanizado | 18x30 | 500 Kg')], max_length=255),
        ),
        migrations.AlterField(
            model_name='familyaction',
            name='rubber_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
