# Generated by Django 5.0.2 on 2024-04-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0008_familyaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyaction',
            name='product_packing',
            field=models.CharField(choices=[('Ardox Polido | 18x30 | 1 Kg', 'Ardox Polido | 18x30 | 1 Kg'), ('Ardox Polido | 18x30 | 500g', 'Ardox Polido | 18x30 | 500g'), ('Ardox Galvanizado | 18x30 | 1 Kg', 'Ardox Galvanizado | 18x30 | 1 Kg'), ('Ardox Galvanizado | 18x30 | 500g', 'Ardox Galvanizado | 18x30 | 500g')], max_length=255),
        ),
    ]
