# Generated by Django 5.0.2 on 2024-04-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0011_alter_familycontactinformation_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycontactinformation',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='familycontactinformation',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familycontactinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
