# Generated by Django 5.0.2 on 2024-04-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0012_alter_familycontactinformation_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycontactinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
