# Generated by Django 5.0.2 on 2024-04-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0014_alter_familycontactinformation_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familycontactinformation',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='familycontactinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
