# Generated by Django 5.0.2 on 2024-04-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0015_alter_familycontactinformation_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
