# Generated by Django 5.0.2 on 2024-04-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0016_alter_family_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyaction',
            name='finished_at',
            field=models.DateTimeField(default=None),
        ),
    ]
