# Generated by Django 5.0.2 on 2024-04-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0020_alter_familyaction_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyaction',
            name='finished_at',
            field=models.DateTimeField(),
        ),
    ]
