# Generated by Django 5.0.2 on 2024-04-15 23:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('product_diameter', models.CharField(max_length=255)),
                ('storage_location', models.CharField(max_length=255, unique=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='StockAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída')], max_length=10)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('family', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'verbose_name': 'Ação estoque',
            },
        ),
        migrations.CreateModel(
            name='StockChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('original_value', models.TextField()),
                ('modified_value', models.TextField()),
                ('stock_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockaction')),
            ],
        ),
    ]
